import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Cormorant_Garamond,
  Lato,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/Navbar/Navbar";
import Footer from "@/components/custom/common/footer";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import QueryClint from "@/lib/QueryClint";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorant",
  display: "swap",
});

// Configure Lato for body text
const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={` ${cormorant.variable} ${lato.variable} antialiased`}>
        <QueryClint>
          <NuqsAdapter>
            <Navbar />
            {children}
            <Footer />
          </NuqsAdapter>
        </QueryClint>
        <Toaster />
      </body>
    </html>
  );
}
